
import Herosection from "../components/Herosection";
export const metadata = {
    title: 'About',
    description: 'About Us of gulfam saifi | Generated by gulfam saifi, It is the developed by me. and it is the movies and series exploring website.',
    metadataBase: new URL('https://gulfam.in'),
    generator: 'gulfam',
    applicationName: 'gulfam',
    referrer: 'origin-when-cross-origin',
    keywords: ['Next.js', 'React', 'JavaScript'],
    authors: [{ name: 'gulfam', url:'https://gulfam.in' }, { name: 'gulfam saifi', url: 'https://gulfam.in' }],
    creator: 'gulfam saifi',
    publisher: 'gulfam saifi',
    type: 'manufacturer,architecture',
      publishedTime: '2023-01-01T00:00:00.000Z',
      archives: ['https://gulfam.in/about'],
      bookmarks: ['https://gulfam.in/door'],
    formatDetection: {
      email: 'info@gulfam.in',
      address: 'noida sector-83 A-Block 218-219 pin-201305',
      telephone: '9873250016',
    },
    robots: {
      noindex: true,
      follow: true,
      nocache: true,
      googleBot: {
        noindex: true,
        nofollow: true,
        noimageindex: true,
        'max-video-preview': -1,
        'max-image-preview': 'large',
        'max-snippet': -1,
      },
    },
    icons: {
      icon: [{ url: '/icon.png' }, new URL('/icon.png', 'https://example.com')],
      shortcut: ['/shortcut-icon.png'],
      apple: [
        { url: '/apple-icon.png' },
        { url: '/apple-icon-x3.png', sizes: '180x180', type: 'image/png' },
      ],
      other: [
        {
          rel: 'apple-touch-icon-precomposed',
          url: '/apple-touch-icon-precomposed.png',
        },
      ],
    },
    verification: {
      google: 'google',
      yandex: 'yandex',
      yahoo: 'yahoo',
      other: {
        me: ['my-email', 'my-link'],
      },
    },
  }
const About = () => {
    return (
        <Herosection title={"OUR STORY"} imageUrl ={"/about1.svg"} />
    );
};

export default About;