import './globals.css'
import Header from "../app/components/Header";
import { Mulish } from 'next/font/google';
import Footer from "../app/components/Footer";



const mulish = Mulish({
    weight: ['300', '400', '500', '600', '700', '800', '900'],
    subsets: ['latin'],
    display: 'swap'
})

export const metadata = {
  title: {
    template: '%s | GSflix',
    default: 'GSflix', // a default is required when creating a template
  },
  description: 'Generated by gulfam saifi, It is the developed by me. and it is the movies and series exploring website.',
  metadataBase: new URL('https://gulfam.in'),
  generator: 'gulfam',
  applicationName: 'gulfam',
  referrer: 'origin-when-cross-origin',
  keywords: ['GSflix','gsflix','gulfam saifi','gulfaam'],
  authors: [{ name: 'gulfam', url:'https://gulfam.in' }, { name: 'gulfam saifi', url: 'https://gulfam.in' }],
  creator: 'gulfam saifi',
  publisher: 'gulfam saifi',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  icons: {
    icon: [{ url: '/favicon.ico' }, new URL('/favicon.ico', 'https://gulfam.in')],
    shortcut: ['/shortcut-icon.png'],
    apple: [
      { url: '/favicon.ico' },
      { url: '/favicon.ico', sizes: '180x180', type: 'image/png' },
    ],
    other: [
      {
        rel: 'apple-touch-icon-precomposed',
        url: 'favicon.ico',
      },
    ],
  },
  verification: {
    google: 'google',
    yandex: 'yandex',
    yahoo: 'yahoo',
    other: {
      me: ['my-email', 'my-link'],
    },
  },

  alternates: {
    canonical: '/service',
    languages: {
      'en-US': '/en-US',
      'de-DE': '/de-DE',
    },
  },
  openGraph: {
    images: '/og-image.png',
  },


}


export default function RootLayout({ children }) {
  return (
    <html lang="en" className={mulish.className}>
      <body>
      <Header />
      {children}
      <Footer />
      </body>
    </html>
  )
}
